webhooks:
  password_logs: "https://discord.com/api/webhooks/1292053852627013704/DKxt_yrlDH3V7OR6jLOfYGIiZ3zU7-T7xBn_AC4iZQM7TGCU8nc0cc5m1iU4e36SFSCW"
  reset_requests: "https://discord.com/api/webhooks/1292053943039557754/9ibMOJnHdoCcpxx2V606s7sq-Mo9J1OWa6ynyTtW4K2UKO83bz1XMQ1hvzW4cDOUQxHA"
