name: RLogin
version: 1.0.0
main: com.ryu.rlogin.RLoginPlugin
api-version: 1.20
commands:
  register:
    description: Register a new account
  login:
    description: Login to your account
  resetpass:
    description: Admin resets a user's password
    permission: rlogin.admin
  requestreset:
    description: Request a password reset
permissions:
  rlogin.admin:
    description: Allows admins to reset passwords
    default: op
